In [31]:
#import nltk
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
from sklearn.metrics import pairwise_distances
import sklearn

In [8]:
text = ["wookie stormtrooper",
        "harry potter",
        "wookie stormtrooper stormtrooper",
        "hairy wookie stormtrooper",
        "hairy harry potter"]

In [11]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(text)
print(vectorizer.get_feature_names())

['hairy', 'harry', 'potter', 'stormtrooper', 'wookie']


In [12]:
print(X.toarray())

[[0 0 0 1 1]
 [0 1 1 0 0]
 [0 0 0 2 1]
 [1 0 0 1 1]
 [1 1 1 0 0]]


In [44]:
X

array([[0, 0, 0, 1, 1],
       [0, 1, 1, 0, 0],
       [0, 0, 0, 2, 1],
       [1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0]])

In [25]:
df = pd.DataFrame(X, columns=vectorizer.get_feature_names())

In [26]:
df

hairy  harry  potter  stormtrooper  wookie
0      0      0       0             1       1
1      0      1       1             0       0
2      0      0       0             2       1
3      1      0       0             1       1
4      1      1       1             0       0

In [28]:
distances = pairwise_distances(df)

In [29]:
distances

array([[0.        , 2.        , 1.        , 1.        , 2.23606798],
       [2.        , 0.        , 2.64575131, 2.23606798, 1.        ],
       [1.        , 2.64575131, 0.        , 1.41421356, 2.82842712],
       [1.        , 2.23606798, 1.41421356, 0.        , 2.        ],
       [2.23606798, 1.        , 2.82842712, 2.        , 0.        ]])

In [32]:
sklearn.metrics.pairwise.cosine_distances(df)

array([[0.        , 1.        , 0.0513167 , 0.18350342, 1.        ],
       [1.        , 0.        , 1.        , 1.        , 0.18350342],
       [0.0513167 , 1.        , 0.        , 0.22540333, 1.        ],
       [0.18350342, 1.        , 0.22540333, 0.        , 0.66666667],
       [1.        , 0.18350342, 1.        , 0.66666667, 0.        ]])

In [39]:
list_of_rows = []
for row in df.iterrows(): 
    list_of_rows.append(list(row))

In [46]:
list_of_distances = []
for index in X:
    for index_2 in X:
        euclidian = pairwise_distances(index.reshape(-1, 1), index_2.reshape(-1, 1))
        list_of_distances.append(euclidian)

In [47]:
list_of_distances

[array([[0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 1.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.]]),
 array([[0., 1., 1., 0., 0.],
        [0., 1., 1., 0., 0.],
        [0., 1., 1., 0., 0.],
        [1., 0., 0., 1., 1.],
        [1., 0., 0., 1., 1.]]),
 array([[0., 0., 0., 2., 1.],
        [0., 0., 0., 2., 1.],
        [0., 0., 0., 2., 1.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 0.]]),
 array([[1., 0., 0., 1., 1.],
        [1., 0., 0., 1., 1.],
        [1., 0., 0., 1., 1.],
        [0., 1., 1., 0., 0.],
        [0., 1., 1., 0., 0.]]),
 array([[1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 1.]]),
 array([[0., 0., 0., 1., 1.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 1.]]),
 array([[0., 1., 1., 0., 0.],
        [1., 0., 0., 1., 1.],
        [1., 0., 0., 1., 1.]

In [42]:
vect = CountVectorizer()
data = vect.fit_transform(text).todense()

In [43]:
data

matrix([[0, 0, 0, 1, 1],
        [0, 1, 1, 0, 0],
        [0, 0, 0, 2, 1],
        [1, 0, 0, 1, 1],
        [1, 1, 1, 0, 0]])